import { z } from "zod";

export const ProductSchema = z
  .object({
    id: z.string().min(1, "Product ID is required").optional(),
    sellerId: z.string().min(1, "Seller ID is required").optional(),
    title: z.string().min(1, "Product title is required"),
    description: z.string().min(1, "Description is required"),
    price: z.string().min(1, 'Price is required'),
    discount: z.string().min(1, 'Discount is required (enter 0 if no discount)'),
    currency: z.union([z.literal("$ USD"), z.literal("€ EURO"), z.literal("₦ NGN")]),
    images: z.any().array().min(1, "At least one image is required"),
    category: z.literal(["Tops","Bottoms","Dresses","Outerwear","Shoes","Accessories","Bags","Underwear","Swimwear","Activewear","Other"]),
    subCategory: z.literal([
  // Tops
  "T-Shirts",
  "Polo Shirts",
  "Tank Tops",
  "Blouses",
  "Dress Shirts",
  "Henleys",
  "Sweatshirts",
  "Hoodies",
  "Crop Tops",
  "Tunics",

  // Bottoms
  "Jeans",
  "Chinos",
  "Dress Pants",
  "Joggers",
  "Leggings",
  "Shorts",
  "Cargo Pants",
  "Skirts",
  "Capris",
  "Overalls",

  // Dresses
  "Casual Dresses",
  "Maxi Dresses",
  "Mini Dresses",
  "Midi Dresses",
  "Bodycon Dresses",
  "Wrap Dresses",
  "Shirt Dresses",
  "Evening Gowns",
  "Cocktail Dresses",
  "Sweater Dresses",

  // Outerwear
  "Jackets",
  "Blazers",
  "Coats",
  "Parkas",
  "Bomber Jackets",
  "Denim Jackets",
  "Trench Coats",
  "Puffer Jackets",
  "Vests",
  "Raincoats",

  // Shoes
  "Sneakers",
  "Loafers",
  "Boots",
  "Sandals",
  "Heels",
  "Flats",
  "Dress Shoes",
  "Slip-Ons",
  "Oxfords",
  "Espadrilles",

  // Accessories
  "Hats",
  "Belts",
  "Scarves",
  "Gloves",
  "Sunglasses",
  "Wallets",
  "Ties",
  "Watches",
  "Hair Accessories",
  "Jewelry",

  // Bags
  "Backpacks",
  "Tote Bags",
  "Crossbody Bags",
  "Clutches",
  "Shoulder Bags",
  "Duffel Bags",
  "Messenger Bags",
  "Satchels",
  "Mini Bags",
  "Laptop Bags",

  // Underwear
  "Boxers",
  "Briefs",
  "Trunks",
  "Bras",
  "Panties",
  "Camisoles",
  "Lingerie Sets",
  "Thermals",
  "Sports Underwear",
  "Shapewear",

  // Swimwear
  "Bikinis",
  "One-Piece Swimsuits",
  "Tankinis",
  "Swim Shorts",
  "Rash Guards",
  "Swim Briefs",
  "Cover-Ups",
  "Monokinis",
  "Board Shorts",
  "Swim Dresses",

  // Activewear
  "Gym Shorts",
  "Sports Bras",
  "Leggings",
  "Tracksuits",
  "Compression Wear",
  "Athletic T-Shirts",
  "Tank Tops",
  "Joggers",
  "Hoodies",
  "Yoga Pants",

  // Other
  "Custom Wear",
  "Uniforms",
  "Costumes",
  "Maternity Wear",
  "Workwear",
  "Ethnic Wear",
  "Festival Outfits",
  "Seasonal Clothing",
  "Vintage",
  "Miscellaneous",
]),    
    condition: z.literal(["new", "used"]),
    size: z.union([
      z.literal(["One Size", "XS", "S", "M", "L", "XL", "XXL"]), // alpha + one size
      z.string().regex(/^\d+$/, "Numeric size must be digits only"), // numeric like 28, 30, 42...
    ]),
    gender: z.literal(["Men", "Women", "Unisex"]),
    brand: z.string().optional(),
    color: z.string().optional(),
    material: z.string().optional(),
    sku: z.string().optional(),
    location: z.string().optional(),
    views: z.number().optional(),
  });
